export type MockServerData = {
  titles: string[],
  descriptions: string[],
  cities: string[],
  previewImages: string[],
  images: string[][],
  isPremiumOffers: string[],
  isFavoritesOffers: string[],
  ratings: string[],
  houseTypes: string[],
  roomsCount: string[],
  guestsCount: string[],
  prices: string[],
  facilities: string[][],
  authors: string[],
  emails: string[],
  avatars: string[],
  usersTypes: string[],
  coordinates: string[][],
}
